condition_number: 100
config: experiments/numerical/configs/mse_nsamples_cov_5.yml
n_features: 5
n_iterations_max: 100
n_jobs: -1
n_points: 50
n_trials: 1000
results_path: results/numerical/mse_estimation_cov/5
samples_power_end: 5
seed: 7777
show_plots: false
