condition_number: 100
config: experiments/numerical/configs/mse_nfeatures_64_nsamples_128.yml
n_features: 64
n_iterations_max: 100
n_jobs: -1
n_matrices:
- 3
- 5
- 20
- 30
- 40
- 60
- 80
- 100
- 1000
n_samples: 128
n_trials: 100
results_path: results/numerical/mse_nmatrices/64_128
seed: 7777
show_plots: false
