condition_number: 100
config: experiments/numerical/configs/mse_nfeatures_5_nsamples_7.yml
n_features: 5
n_iterations_max: 100
n_jobs: -1
n_matrices:
- 3
- 5
- 20
- 30
- 40
- 60
- 80
- 100
- 1000
- 10000
n_samples: 7
n_trials: 1000
results_path: results/numerical/mse_nmatrices/5_7
seed: 7777
show_plots: false
