condition_number: 100
config: experiments/numerical/configs/mse_nsamples/mse_nfeatures_64_nmatrices_10.yml
n_features: 64
n_iterations_max: 100
n_jobs: -1
n_matrices: 10
n_samples:
- 65
- 68
- 80
- 100
- 150
- 200
- 300
n_trials: 100
results_path: /home/ammarmian/papers/icml_2024/code/mse_nsamples/2024-02-01_17-05-05
seed: 7777
show_plots: false
