condition_number: 100
config: experiments/numerical/configs/mse_iteration.yml
n_features: 5
n_iterations_max: 100
n_jobs: -1
n_matrices: 100
n_samples: 49
n_trials: 10000
results_path: results/numerical/mse_iteration
seed: 7777
show_plots: false
